### ISSUE TITLE
does it support regex?

### ISSUE THREAD

**Issue by fullmooninu** [temoto/nginx-lint#2]
With this:

```
if ($rule_0 = "21"){
        rewrite ^/(.*).(gif|jpg|png)$ /$1_2x.$2;
}
```

Getting: 

```
unexpected "("
expecting directive argument or ";"
```

**Comment by temoto** [comment]
Wow, that's a good question, to be honest, I haven't touch this project in a long time, need some time to recall how its grammar works.

**Comment by temoto** [comment]
Turns out, these symbols were not allowed in argument of rewrite (or any other instruction) when argument string is unquoted: `(){}`. I am looking for a way to fix it now.

**Comment by temoto** [comment]
@fullmooninu fixed, thanks for bumping up this old project. I had lots of fun programming in Haskell again.

**Comment by fullmooninu** [comment]
Wow, pretty nice! 

I'm also messing around with haskell. Haven't done much useful with it yet. 

Will test this new version out. Thanks =)
