### ISSUE TITLE
unexpected "{"

### ISSUE THREAD

**Issue by fullmooninu** [temoto/nginx-lint#3]
$ ./build/nginx-lint/nginx-lint ~/mounts/mount1/servers/nginx/conf/nginx.conf
"/home/inu/mounts/mount1/servers/nginx/conf/nginx.conf" (line 16, column 6):
unexpected "{"
expecting natural, "\"", plain string or ";"

**Comment by temoto** [comment]
Hello. Can you post nginx.conf here or privately to temotor@gmail.com ?

**Comment by fullmooninu** [comment]
I'm sorry, I lost context of this already. I think it wasn't working on any config I tried.

**Comment by temoto** [comment]
@fullmooninu sorry I'm not working on this project.
